# Travis CI Configuration
language: python
python:
  - "2.7"
# command to install dependencies
virtualenv:
    system_site_packages: false
before_install:
    - pip install codecov
    - pip install flake8
    - pip install coverage
    - pip install -r requirements.txt
install:
    - python setup.py develop
script:
    - coverage run -m unittest discover
    - flake8 .
after_success:
    - codecov

